Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"

  # Nodo maestro
  config.vm.define "AMKUBDEVRKEN01A" do |master|
    master.vm.hostname = "AMKUBDEVRKEN01A"
    master.vm.network "private_network", ip: "10.98.72.101"
    master.vm.provider "libvirt" do |lv|
      lv.memory = 4096
      lv.cpus = 2
    end
    master.vm.provision "shell", inline: <<-SHELL
      apt update
    SHELL
  end

  # Nodo trabajador 1
  config.vm.define "AMKUBDEVRKEN01B" do |worker|
    worker.vm.hostname = "AMKUBDEVRKEN01B"
    worker.vm.network "private_network", ip: "10.98.72.102"
    worker.vm.provider "libvirt" do |lv|
      lv.memory = 4096
      lv.cpus = 2
    end
    worker.vm.provision "shell", inline: <<-SHELL
      apt update
    SHELL
  end

  # Nodo trabajador 2
  config.vm.define "AMKUBDEVRKEN02A" do |worker_2|
    worker_2.vm.hostname = "AMKUBDEVRKEN02A"
    worker_2.vm.network "private_network", ip: "10.98.72.103"
    worker_2.vm.provider "libvirt" do |lv|
      lv.memory = 4096
      lv.cpus = 2
    end
    worker_2.vm.provision "shell", inline: <<-SHELL
      apt update
    SHELL
  end
end
